version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: Alonso2011. # Cambia esta contraseña por una segura
      MYSQL_DATABASE: fleetdb             # Nombre de la base de datos
      MYSQL_USER: admin                   # Usuario creado
      MYSQL_PASSWORD: Alonso2011.     # Contraseña del usuario admin
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
